name: Keep Website Alive

on:
  schedule:
    # This runs every 15 minutes. 
    # Format: "minute hour day month day-of-week"
    - cron: '*/15 * * * *'
  workflow_dispatch: # Allows you to run the ping manually for testing

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping URL
        run: curl -I https://dangsbbq.vercel.app/
